version: '3.8'

services:
  streamlit-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT:-your-project-id}
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME:-i2a2-eda-uploads}
    volumes:
      - ./temp_graficos:/app/temp_graficos
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s